# General Site Settings
title: Compiling life by Willy Alde
email: willy.alde@gmail.com
description: >-
  This is my personal corner of the web, powered by Jekyll and hosted on GitHub Pages. Here, you'll find content related to my professional journey as a dotnet enthusiast.
baseurl: "" # The subpath of your site, e.g., /blog
url: "https://wilvanbil.github.io" # The base hostname & protocol for your site
show_excerpts: true

# Social Media
twitter_username: willyalde
github_username: wilvanbil
linkedin_username: willyalde

# Plugins and Themes
remote_theme: jekyll/minima
minima:
  skin: auto
plugins:
  - jekyll-remote-theme

# SEO and Analytics
google_analytics: UA-NNNNNNNN-N
lsi: false

# Markdown and Syntax Highlighting
highlighter: rouge
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
gist:
  noscript: false

# Build Configuration
safe: true
source: .
incremental: false

# Excluded Files and Folders
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
